export default {
    FETCH_PROFILES:"FETCH_PROFILES",
    CREATE_PROFILE:"CREATE_PROFILE",
    FETCH_CURRENTUSER: "FETCH_CURRENTUSER",
    LOGOUT_USER: "LOGOUT_USER",
    FETCH_BOOKMARKS : "FETCH_BOOKMARKS",
    SELECT_PROFILE: "SELECT_PROFILE",
    FETCH_USER_BOOKMARK: "FETCH_USER_BOOKMARK",
    CREATE_BOOKMARK: "CREATE_BOOKMARK"
}