export default {
    FETCH_PROFILES:"FETCH_PROFILES",
    CREATE_PROFILE:"CREATE_PROFILE",
    FETCH_CURRENTUSER: "FETCH_CURRENTUSER",
    LOGOUT_USER: "LOGOUT_USER",
    FETCH_BOOKMARKS : "FETCH_BOOKMARKS",
    SELECT_PROFILE: "SELECT_PROFILE"
}